### ISSUE TITLE
Min/max date

### ISSUE THREAD

**Issue by RomeroDiver** [mobinni/material-date-picker#15]
Hi,
Could I recommend that You add check for min/max date attribute - if that's a Date object, than use moment(date) and not moment(string, string)?

**Comment by mobinni** [comment]
Thanks for the suggestion I will look into this! But at first glance I think I made it string, string because I found it's easier to validate a single form of input.

**Comment by mobinni** [comment]
At closer evaluation I did it this way, since in any given application you have a specific date format you will follow. Min and Max dates will not change so you fill them in according to your specific date format in plain text, or convert your Date Object to string. then your specific format is used to parse it to a valid moment object which is then used by my code.
